/**
Graph UIView.  The appearance and display of a pie chart completely generated by Core Graphics.  
Simply send this object a list of values and colors to generate the chart
 
@author Team Axe, LLC. http://www.teamaxe.org, Submitted to Public Domain
@class GraphView
@date 09/05/2010
@file
*/

#import <UIKit/UIKit.h>

@interface GraphView : UIView {
    	
}

@property (nonatomic, retain) NSArray *pieValues;   /**< float pieValues in number of degrees out of 360 */
@property (nonatomic, retain) NSArray *pieColors;   /**< UIColors that map to each Value */

@end
